### ISSUE TITLE
잘못된 값

### ISSUE THREAD

**Issue by sunrabbit123** [sunwoo0706/Grig#1]
https://github.com/sunwoo0706/Grig/blob/master/src/components/layouts/Modals/Modal.tsx#L41

revalidate 주기는 24시간으로 KST 기준으로 새벽 3시마다 진행됩니다~

자세한 사항은 https://github.com/GRI-G/GRIG-API/blob/main/.github/workflows/Update.yml

**Comment by sunwoo0706** [comment]
@sunrabbit123 클라이언트 `getStaticProps` `revalidate` 기준입니다 ~
https://github.com/sunwoo0706/Grig/blob/80fc42434b4cf55688251a1dfcd3291d5af1c64d/src/pages/index.tsx#L34

**Comment by sunwoo0706** [comment]
추후에 docs에 추가하도록 할게요 !
